### ISSUE TITLE
Layout, style, sounds, etc.

### ISSUE THREAD

**Issue by G-GamesStudios** [G-GamesStudios/ugface.github.io#3]
Here is the main discussion of the website design.

**Comment by Ugface-TurboWarb** [comment]
Layout; Sub-headings at the top which take you to a new page 
Pages / Sub-headings (in this order): Home, News & Announcements, Featured 
NO Sounds
Chat Bar At Bottom

Question - Will you be coding this using html?

**Comment by G-GamesStudios** [comment]
Okay... And I will code this literally with HTML and CSS.

**Comment by Ugface-TurboWarb** [comment]
I'll make the website and feature you

**Comment by Ugface-TurboWarb** [comment]
Thanks,
@Ugface-TurboWarb
